<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <Title>World of Warcraft Launcher</Title>
        <Authors>MadBuffoon</Authors>
        <Company>Private Server Company</Company>
        <PackageProjectUrl></PackageProjectUrl>
        <PackageIcon>app.png</PackageIcon>
        <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
        <ApplicationIcon>wow_app.ico</ApplicationIcon>
        <AssemblyName>$(MSBuildProjectName)</AssemblyName>
        <IsPublishable>True</IsPublishable>
        <Product>Launcher</Product>
        <Copyright></Copyright>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <Version>7.2</Version>
        <RepositoryUrl></RepositoryUrl>
        <RepositoryType></RepositoryType>
        <BaseOutputPath>F:\Games\World of Warcraft\Coding\WoWUpdater\Build</BaseOutputPath>
        <PublicSign>false</PublicSign>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugType>none</DebugType>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <OutputPath>Bin\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <OutputPath>Bin\Release\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="images\Button-Click.png" />
        <None Remove="images\Button-Disabled.png" />
        <None Remove="images\Button-Hover.png" />
        <None Remove="images\Button.png" />
        <None Remove="images\Close-Click.PNG" />
        <None Remove="images\Close-Hover.png" />
        <None Remove="images\Close.PNG" />
        <None Remove="images\Indicator-Green.PNG" />
        <None Remove="images\Indicator-Red.PNG" />
        <None Remove="images\Indicator-Yellow.PNG" />
        <None Remove="images\PatchBar.png" />
        <None Remove="images\Window.png" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="wow_app.ico" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="images\Button-Click.png">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Button-Disabled.png">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Button-Hover.png">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Button.png">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Close-Click.PNG">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Close-Hover.png">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Close.PNG">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Indicator-Green.PNG">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Indicator-Red.PNG">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Indicator-Yellow.PNG">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\PatchBar.png">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <Resource Include="images\Window.png">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Resource>
        <None Remove="images\TextInput.png" />
        <Resource Include="images\TextInput.png" />
        <None Remove="MadClownWorld.snk" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\Resources\app.png">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Properties\" />
    </ItemGroup>
    <ItemGroup>
        <None Include="WebView2Files\**\*.*">
            <Pack>True</Pack>
            <PackagePath>WebView2Files\</PackagePath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="K4os.Hash.xxHash" Version="1.0.8" />
      <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2592.51" />
    </ItemGroup>
</Project>
